### PR TITLE
feat: 🚀 Mediapipe version 0.9.2.1

### PR DESCRIPTION
**Pull request by onuralpszr**
Hello, New version of MP 0.9.2.1 released and It would be nice to use those features. 

Changes : https://github.com/google/mediapipe/releases/tag/v0.9.2.1

### CODE REVIEW

**Comment by cansik** [comment]
Thanks, I still have to build it locally as github doesn't provide arm64 MacOS runners. I will have a look at it tomorrow.

**Comment by onuralpszr** [comment]
Hopefully, they will release this year (i saw messages in  github action issue) 

I am also looking for opencv4 builds. In certain projects, you can easily use cv4 as well. A separate build would be nice.

**Comment by cansik** [comment]
@onuralpszr Thanks again for the PR, but it took me longer than expected to fix everything and I switched now to a new powershell script to build mediapipe-silicon. Version [v0.9.2.1](https://github.com/cansik/mediapipe-silicon/releases/tag/v0.9.2.1) is already built and after testing I will release it on pypi as well.

I am sorry but I can not merge your PR because many of the changes are already obsolete, but thanks for your effort.

**Comment by onuralpszr** [comment]
> @onuralpszr Thanks again for the PR, but it took me longer than expected to fix everything and I switched now to a new powershell script to build mediapipe-silicon. Version [v0.9.2.1](https://github.com/cansik/mediapipe-silicon/releases/tag/v0.9.2.1) is already built and after testing I will release it on pypi as well.
> 
> I am sorry but I can not merge your PR because many of the changes are already obsolete, but thanks for your effort.

No problem :) I am glady you look into it. Also notice "latest" mediapipe is can work with apple silicon as well. (I tested) but it seems to be use "universal" method and I didn't check was it using metal or not but something to consider as well.

**Comment by cansik** [comment]
@onuralpszr Yes I have seen it as well! I could install it on my system but it seemed that it is not completely backwards compatible because of the new solutions. Not sure if I made a mistake on my side, but I will check it again.

Hopefully Google is finally able to build arm packages as well 🎉 it's already been 2 years since the release of the M1 hardware 🙈

**Comment by onuralpszr** [comment]
> @onuralpszr Yes I have seen it as well! I could install it on my system but it seemed that it is not completely backwards compatible because of the new solutions. Not sure if I made a mistake on my side, but I will check it again.
> 
> Hopefully Google is finally able to build arm packages as well tada it's already been 2 years since the release of the M1 hardware see_no_evil

They made soo many changes like iris and face mesh is different some parts are still same but my old python code was failing and I had to read and re-fix them all again plus they bring "vision" import so it is also effect as well. You are not doing something wrong, it just they changed it.

**Pull request closed without merging**
